{{- if .Values.serviceAccount.create -***REMOVED******REMOVED***
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "visits.serviceAccountName" . ***REMOVED******REMOVED***
  labels:
    {{- include "visits.labels" . | nindent 4 ***REMOVED******REMOVED***
  {{- with .Values.serviceAccount.annotations ***REMOVED******REMOVED***
  annotations:
    {{- toYaml . | nindent 4 ***REMOVED******REMOVED***
  {{- end ***REMOVED******REMOVED***
{{- end ***REMOVED******REMOVED***
