
@host=4.230.152.237

###
GET http://{{host***REMOVED******REMOVED***/actuator

###
GET http://{{host***REMOVED******REMOVED***/api/customer/actuator

###
GET http://{{host***REMOVED******REMOVED***/api/customer/owners

###
GET http://{{host***REMOVED******REMOVED***/api/customer/owners/4

###
POST http://{{host***REMOVED******REMOVED***/actuator/refresh

###
GET http://{{host***REMOVED******REMOVED***/api/customer/owners/ 
http://{{host***REMOVED******REMOVED***/api/customer/petTypes
http://{{host***REMOVED******REMOVED***/api/customer/owners/3/pets/4
http://{{host***REMOVED******REMOVED***/api/customer/owners/6/pets/8/

###
http://{{host***REMOVED******REMOVED***/api/vet/vets
http://{{host***REMOVED******REMOVED***/api/visit/owners/6/pets/8/visits
http://{{host***REMOVED******REMOVED***/api/visit/owners/6/pets/8/visits

###
GET http://{{host***REMOVED******REMOVED***/api/visit/owners/6/pets/8/visits