apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wavefront-proxy
    name: wavefront-proxy
  name: wavefront-proxy
  namespace: spring-petclinic
***REMOVED***
  replicas: 1
  selector:
    matchLabels:
      app: wavefront-proxy
  template:
    metadata:
      labels:
        app: wavefront-proxy
    ***REMOVED***
      containers:
      - name: wavefront-proxy
      ***REMOVED*** "{{ .Values.image.repository ***REMOVED******REMOVED***:{{ .Values.image.tag | default .Chart.AppVersion ***REMOVED******REMOVED***"
        imagePullPolicy: Always
      ***REMOVED***
        - name: WAVEFRONT_URL
      ***REMOVED***
       ***REMOVED***
               name: wavefront
               key: wavefront-url
        - name: WAVEFRONT_TOKEN
      ***REMOVED***
       ***REMOVED***
               name: wavefront
               key: wavefront-api-token
        # Uncomment the below lines to consume Zipkin/Istio traces
        - name: WAVEFRONT_PROXY_ARGS
          value: --traceZipkinListenerPorts 9411 --traceZipkinApplicationName spring-petclinic-k8s
        ports:
        - containerPort: 2878
          protocol: TCP
        # Uncomment the below lines to consume Zipkin/Istio traces
        - containerPort: 9411
          protocol: TCP
        securityContext:
          privileged: false