***REMOVED***
***REMOVED***
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-vets-service
***REMOVED***
 

***REMOVED***
***REMOVED***
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-customers-service
***REMOVED***
  resources: 
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi  

***REMOVED***
***REMOVED***
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-visits-service
***REMOVED***

***REMOVED***
***REMOVED***
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-api-gateway
***REMOVED***
