***REMOVED***
 ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: APPLICATIONINSIGHTS_CONNECTION_STRING
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"  
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage" 

***REMOVED***
 ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/vets_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: APPLICATIONINSIGHTS_CONNECTION_STRING
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage" 

***REMOVED***
 ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: SPRING_DATASOURCE_URL
    value: jdbc:mysql://mysqlandy.mysql.database.azure.com:3306/visits_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db&useSSL=true&serverSslCert=classpath:BaltimoreCyberTrustRoot.crt.pem
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
  - name: APPLICATIONINSIGHTS_CONNECTION_STRING
    value: "f8c35d3c-98fe-48c5-9a42-a3317930260a"    
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage"

***REMOVED***
***REMOVED***
  - name: SPRING_PROFILES_ACTIVE         
    value: "stage"            


