***REMOVED***
***REMOVED***
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-vets-service
***REMOVED***
 

***REMOVED***
***REMOVED***
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-customers-service
***REMOVED*** 

***REMOVED***
***REMOVED***
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-visits-service
***REMOVED***

***REMOVED***
***REMOVED***
    repository: springpetacr.azurecr.io/petclinic/spring-petclinic-api-gateway
***REMOVED***
  resources: 
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi  