vets:
  image:
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-vets-service
    tag: latest
 

customers:
  image:
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-customers-service
    tag: latest
  resources: 
    limits:
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 1Gi  

visits:
  image:
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-visits-service
    tag: latest

api-gateway:
  image:
    repository: azurespringacr.azurecr.io/petclinic/spring-petclinic-cloud-api-gateway
    tag: latest
