keyvault:
  enabled: false

***REMOVED***
***REMOVED***
    repository: spreg.azurecr.io/petclinic/spring-petclinic-cloud-vets-service
***REMOVED***
 
***REMOVED***
***REMOVED***
    repository: spreg.azurecr.io/petclinic/spring-petclinic-cloud-customers-service
***REMOVED*** 

***REMOVED***
***REMOVED***
    repository: spreg.azurecr.io/petclinic/spring-petclinic-cloud-visits-service
***REMOVED***

***REMOVED***
***REMOVED***
    repository: spreg.azurecr.io/petclinic/spring-petclinic-cloud-api-gateway
***REMOVED***
  resources: 
    limits:
      memory: 2Gi
    requests:
      cpu: 1000m
      memory: 1Gi  
  