apiVersion: v1
kind: Service
metadata:
  name: azure-vote-back
***REMOVED***
  ports:
  - port: 6379
  selector:
    app: azure-vote-back
---
apiVersion: v1
kind: Service
metadata:
  name: azure-vote-front
***REMOVED***
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-vote-front