
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    - key: mysql-url                          
      objectName: mysql-url     
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    userAssignedIdentityID: "40c38cae-73af-419a-8ce5-62d20acc0044"
    keyvaultName: "kvspr"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
          objectName: mysql-url
***REMOVED***                       # object types: secret, key or cert
***REMOVED***                     # [OPTIONAL] object versions, default to latest if empty
***REMOVED***
    ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** 
    tenantId: "ed10ace5-fd47-4660-bc91-7c764a302f4f"

