
{{- if .Values.keyvault.enabled -***REMOVED******REMOVED***
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-secret
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***      
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    userAssignedIdentityID: "40c38cae-73af-419a-8ce5-62d20acc0044"
    keyvaultName: "kvspr"
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
    ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED*** 
    tenantId: "ed10ace5-fd47-4660-bc91-7c764a302f4f"
{{- end ***REMOVED******REMOVED***
