---
kind: ConfigMap
apiVersion: v1
metadata:
  name: petclinic-config
data:
  application.yaml: |-
    server:
      shutdown: graceful
      lifecycle:
        timeout-per-shutdown-phase: 15
      port: 8080
      compression:
  ***REMOVED***
        mime-types: application/json,text/css,application/javascript
        min-response-size: 2048

    # Logging
    logging.level.org.springframework: INFO

    # Metrics
    management:
      endpoint:
        health:
          probes:
      ***REMOVED***
      health:
        livenessState:
    ***REMOVED***
        readinessState:
    ***REMOVED***
        restart:
    ***REMOVED***
        metrics:
    ***REMOVED***
        prometheus:
    ***REMOVED***
      endpoints:
        web:
          exposure:
            include: '*'
      metrics:
        export:
          prometheus:
      ***REMOVED***
          wavefront:
      ***REMOVED***

    customers-service-id: http://customers-service.spring-petclinic.svc.cluster.local:8080
    visits-service-id: http://vists-service.spring-petclinic.svc.cluster.local:8080

    ***REMOVED***
      datasource:
        schema: classpath*:db/mysql/schema.sql
        data: classpath*:db/mysql/data.sql
        platform: mysql
        initialization-mode: always

      jpa:
        show-sql: true
        hibernate:
          ddl-auto: none
          generate-ddl: false
      sleuth:
        sampler:
          probability: 1.0
      ***REMOVED***
          # Allow the microservices to override the remote properties with their own System properties or config file
          allow-override: true
          # Override configuration with any local property source
          override-none: true
      messages:
        basename: messages/messages
    ***REMOVED***
    ***REMOVED***
          discovery:
      ***REMOVED***
        loadbalancer:
          ribbon:
      ***REMOVED***
        gateway:
          x-forwarded:  
      ***REMOVED*** 
            for-enabled: true 
            proto-enabled: true 
            host-append: false  
            port-append: false  
            proto-append: false
          routes:
            - id: vets-service
              uri: http://vets-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/vet/**
              filters:
                - StripPrefix=2
            - id: visits-service
              uri: http://visits-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/visit/**
              filters:
                - StripPrefix=2
            - id: customers-service
              uri: http://customers-service.spring-petclinic.svc.cluster.local:8080
              predicates:
                - Path=/api/customer/**
              filters:
                - StripPrefix=2
    ***REMOVED***
      cache:
        ttl: 60
        heap-size: 101

