---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: spring-petclinic  
***REMOVED***
  ports:
  - name: "http"
    port: 8080
    targetPort: 8080
  selector:
    app: visits-service
status:
  loadBalancer: {***REMOVED***
