---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
  namespace: spring-pet-clinic
***REMOVED***
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer
status:
  loadBalancer: {***REMOVED***
