---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: spring-petclinic
***REMOVED***
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: vets-service
status:
  loadBalancer: {***REMOVED***
