---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
  namespace: spring-pet-clinic  
***REMOVED***
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: visits-service
status:
  loadBalancer: {***REMOVED***
