apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-monolith
  labels:
    app: petclinic-monolith
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-monolith
  template:
    metadata:
      labels:
        app: petclinic-monolith
    spec:
      containers:
        - name: petclinic-monolith
          image: petclinic-monolith
          ports:
            - containerPort: 8080