apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic-monolith
  labels:
    app: petclinic-monolith
***REMOVED***
  replicas: 1
  selector:
    matchLabels:
      app: petclinic-monolith
  template:
    metadata:
      labels:
        app: petclinic-monolith
    ***REMOVED***
      containers:
        - name: petclinic-monolith
        ***REMOVED*** petclinic-monolith
          ports:
            - containerPort: 8080