apiVersion: v1
kind: Service
metadata:
  name: petclinic-monolith
***REMOVED***
  type: LoadBalancer
  selector:
    app: petclinic-monolith
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080