server.port: 8888
***REMOVED***
***REMOVED***
  ***REMOVED***
      server:
        git:
          uri: https://github.com/spring-petclinic/spring-petclinic-microservices-config
          # Uncomment for local configuration repository:
          # uri: file:///${GIT_REPO***REMOVED***
